server:
  # 应用服务 WEB 访问端口
  port: 8080
  servlet:
    context-path: /springboot-mybatis
spring:
  application:
    # 应用名称
    name: mybatis-plus-demo
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: mysql
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/kai_tuo?serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: doujiyuan
  sql.init.schema-locations: classpath*:sql/user.sql
  sql.init.mode: always
  # jpa根据实体类创建数据表
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
## 生成sql语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
